Update MultipartFields
fastify/fastify-multipart pull request #154
Opened 2020-09-01 10:26 UTC by BlackGlory

If the field names are the same, the value of the field will be an array.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2020-09-01 11:32 UTC, StarpTech approved these changes
lgtm, thanks.

2020-09-01 12:06 UTC, mcollina requested changes
Would you mind to add a test for this type?

2020-09-01 15:14 UTC, BlackGlory commented
@mcollina I did not find a file for testing TypeScript types in the repo, `test/index.test-d.ts` doesn't look like a unit test.

2020-09-02 03:11 UTC, BlackGlory commented
`test/index.test-d.ts` is the v2.0 test file, so I updated it to v3.0.
But IMHO, since the file is not updated with the new version, obviously these tests are not helpful.

2020-09-02 03:28 UTC, BlackGlory commented
Considering the properties of the field type, it seems necessary to split Multipart into two interfaces.
But it will break the examples in the README, because we need to distinguish between different types. I'm not sure if these definitions should be added.

```ts
type Multipart = MultipartField | MultipartFile

interface MultipartField {
  fieldname: string
  value: string
  fieldnameTruncated: boolean
  valueTruncated: boolean
  fields: MultipartFields
}

interface MultipartFile  {
  toBuffer: () => Promise<Buffer>,
  file: NodeJS.ReadableStream,
  filepath: string,
  fieldname: string,
  filename: string,
  encoding: string,
  mimetype: string,
  fields: MultipartFields
}
```

2020-09-02 06:01 UTC, hixus commented
I might also export all interfaces (for example Multipart) so one can use them for own function declarations that use the result

2020-09-02 08:26 UTC, mcollina commented
I don't understand the question. Is this ready to land?

2020-09-02 08:26 UTC, mcollina approved these changes
lgtm

2020-09-02 08:53 UTC, hixus commented
> I don't understand the question. Is this ready to land?

Could be different pr, but for example I might wan't to define separate handler which would take just the Multipart as an argument. Currently not possible without defining it again.

```
const handleFile = async (part: Multipart) => {
  pump(part.file, fs.createWriteStream(part.filename))
}

server.post("/upload", async (req, reply) => {
  const parts = req.parts()
  for await (const part of parts) {
    if (part.file) {
      await handleFile(part)
    } else {
      console.log(part)
    }
  }
  reply.send()
});
```

2020-09-02 09:29 UTC, BlackGlory commented
This PR is ready to merge.

It may take someone more familiar with this project to decide which TypeScript interfaces should be exported, not me.

2020-09-02 13:49 UTC, fox1t requested changes

2020-09-02 13:49 UTC, fox1t commented on index.d.ts
>  interface Multipart {
```suggestion
export interface Multipart {
```

2020-09-02 13:51 UTC, fox1t commented
Nice work! Thanks for you contribution. 
There is one missing export to add, then this PR can be merged.

2020-09-02 14:08 UTC, fox1t approved these changes
LGTM

2020-09-02 16:27 UTC, mcollina approved these changes
lgtm

2020-09-03 18:16 UTC, merged