Add correct type for non-file value
fastify/fastify-multipart pull request #165
Opened 2020-10-13 08:40 UTC by JbIPS

Allow user to declare a field as a non-file value with a generic
`Multipart<T>` to set the correct type of the value.

Closes #162

2020-10-13 09:01 UTC, mcollina commented
Can you please add a unit test?

2020-10-13 14:18 UTC, Ethan-Arrowood requested changes
please add a test using TSD - otherwise this looks good thank you!

2020-10-15 13:09 UTC, JbIPS commented
First time with TSD so tell me if it's not enough

2020-10-15 13:23 UTC, fox1t reviewed
LGTM

2020-10-15 13:23 UTC, fox1t commented on test/index.test-d.ts
> +import fastifyMultipart, {Multipart, MultipartFields} from '..'
Seems that formatting is missing here

2020-10-16 08:42 UTC, JbIPS commented on test/index.test-d.ts
> +import fastifyMultipart, {Multipart, MultipartFields} from '..'
Sorry, fixed that!

2020-10-16 10:18 UTC, mcollina approved these changes
lgtm

2020-10-16 10:19 UTC, mcollina commented
@Ethan-Arrowood you good to land this?

2020-10-16 12:01 UTC, Ethan-Arrowood approved these changes
LGTM!

2020-10-17 08:56 UTC, merged