feat: req.file throws filesize error
fastify/fastify-multipart pull request #207
Opened 2021-03-09 16:38 UTC by brainrepo

Feature proposal:

Allow req.file to throw an error when the file is bigger than the limit

closes #196 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-03-09 16:52 UTC, mcollina requested changes
The approach looks good to me, I've left a few notes.

2021-03-09 16:52 UTC, mcollina commented on test/multipart-small-stream.test.js
> +      reply.code(413).send()
why this change?

2021-03-09 16:52 UTC, mcollina commented on index.js
> +          throw new RequestFileTooLargeError()
are we sure that the only condition for the file being truncated is that it is too large? Maybe it should be a different error.

2021-03-09 17:39 UTC, climba03003 commented
If you specify it in the function `getMultipartFile`, it can not respect the route level options of `throwFileSizeLimit`.

2021-03-10 07:18 UTC, brainrepo commented on test/multipart-small-stream.test.js
> +      reply.code(413).send()
ops, simply my carelessness

2021-03-10 07:58 UTC, mcollina commented
A test is needed.

2021-03-10 08:58 UTC, mcollina approved these changes
lgtm

2021-03-10 09:02 UTC, brainrepo commented
> can you check why CI is failing?

Yes, I am doing it, the ci fails on windows for `ERR_STREAM_PREMATURE_CLOSE`, but in my local fork the CI is passing.

2021-03-10 13:48 UTC, brainrepo commented
> can you check why CI is failing?

I have installed a windows machine on Virtualbox with node 12.21.0 as the CI trying to reproduce the error but everything works fine.

2021-03-10 14:30 UTC, simoneb approved these changes

2021-03-10 17:03 UTC, mcollina commented
@StarpTech could you take a look?

2021-03-11 11:33 UTC, merged

2021-03-11 11:38 UTC, StarpTech commented
Sorry, I had no time yesterday.