feat: part.type for easy type narrowing
fastify/fastify-multipart pull request #422
Opened 2023-03-12 23:08 UTC by nadhifikbarw

Easier type narrowing as discussed #144

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-03-12 23:15 UTC, nadhifikbarw commented
Before  
![image](https://user-images.githubusercontent.com/10264286/224579935-1e9baa8a-45bd-4a63-b5f3-9faf41aba9c8.png)

After  
![image](https://user-images.githubusercontent.com/10264286/224579748-f3dc73f5-cefb-482b-83a8-1257a30e0606.png)

2023-03-13 11:34 UTC, mcollina approved these changes
lgtm

2023-03-13 12:43 UTC, climba03003 approved these changes
It looks better.

2023-03-13 12:51 UTC, Uzlopak requested changes
Just some nitpicking on the typings tests, other than LGTM. Nice work.

2023-03-13 12:51 UTC, Uzlopak commented on test/index.test-d.ts
> +    expectAssignable<string>(data.type)
```suggestion
    expectType<'file'>(data.type)
```

2023-03-13 12:51 UTC, Uzlopak commented on test/index.test-d.ts
>      expectType<string>(req.body.foo.value);
```suggestion
    expectType<'field'>(req.body.foo.type)
    expectType<string>(req.body.foo.value);
```

2023-03-13 13:00 UTC, nadhifikbarw commented
@Uzlopak thanks! that was my initial approach, I thought it won't work since my IDE showing error, but it was only my cache issue.

2023-03-13 13:17 UTC, Uzlopak approved these changes
LGTM

2023-03-13 15:08 UTC, merged