v8
fastify/fastify-multipart pull request #481
Opened 2023-09-25 22:48 UTC by gurgunday

There has been [multiple](https://github.com/fastify/fastify-multipart/issues/447#issuecomment-1704377333) [requests](https://github.com/fastify/fastify-multipart/issues/447#issuecomment-1734334541) to make a major release as we fixed an annoying issue, but so far we've held it back to combine these changes with a rewrite of the plugin

I think as @mcollina said, bumping major is cheap and we can release v9 in the future when the rewrite is complete

Closes #447 and closes #456, closes #289, closes #202

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-09-25 22:56 UTC, mcollina approved these changes
lgtm

2023-09-26 12:15 UTC, Eomm commented
Does it close this issue too https://github.com/fastify/fastify-multipart/issues/464?

2023-09-26 13:29 UTC, gurgunday commented
That one is more about the actual rewrite we wanted to do. Maybe we can remove “restructure” from its title

The following however can be closed as we removed the cause of the bug while providing an alternative that works: https://github.com/fastify/fastify-multipart/issues/435

2023-09-27 18:52 UTC, gurgunday commented
Anyone wants to add a breaking change?

Last call!

2023-09-27 18:54 UTC, Fdawgs requested changes

2023-09-27 18:54 UTC, Fdawgs commented on test/multipart-attach-body.test.js
> +test('should pass the buffer instead of convering to string', async function (t) {
```suggestion
test('should pass the buffer instead of converting to string', async function (t) {
```

2023-09-27 18:54 UTC, Fdawgs commented on README.md
> +Request body key-value pairs can be assigned directly using `attachFieldsToBody: 'keyValues'`. Field values including file buffers will be attached to the body object.
```suggestion
Request body key-value pairs can be assigned directly using `attachFieldsToBody: 'keyValues'`. Field values, including file buffers, will be attached to the body object.
```

2023-09-27 18:56 UTC, Fdawgs commented
Probably also needs a more descriptive PR title rather than v8? 😋

2023-09-28 06:40 UTC, Fdawgs approved these changes

2023-09-28 10:09 UTC, Uzlopak approved these changes
If @Fdawgs approves, I also approve.

2023-09-28 10:59 UTC, merged