Partly closes #496: add missing type
fastify/fastify-multipart pull request #502
Opened 2023-12-27 08:38 UTC by hash0000

Fix type missing. More info in issue #496.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2023-12-27 10:26 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? We use tsd for our types.

2023-12-27 13:19 UTC, mcollina commented
The type test is https://github.com/fastify/fastify-multipart/blob/master/types/index.test-d.ts

2023-12-27 13:21 UTC, hash0000 commented
Does the `files()` and `file()` support all options from the `FastifyMultipartBaseOptions` interface (except `throwFileSizeLimit` and `limits`, of course)?

2023-12-27 13:23 UTC, mcollina commented
I think so, but verify with the code.

2023-12-27 14:27 UTC, hash0000 commented
I'm not sure, but is this the test you meant?

2023-12-27 14:42 UTC, Uzlopak commented
Lets run the tests. Your holistic approach to also test the same thing in javascript is apprecaited.

2023-12-27 15:06 UTC, Uzlopak commented on types/index.test-d.ts
> +    const parts = req.files(options)
hmm. You are type casting options. 

```suggestion
    const parts = req.files({
      limits: { fileSize: 1000, parts: 500 },
      throwFileSizeLimit: true,
      sharedSchemaId: 'schemaId',
      isPartAFile: (fieldName, contentType, fileName) => {
        expectType<string | undefined>(fieldName)
        expectType<string | undefined>(contentType)
        expectType<string | undefined>(fileName)
        return true
      }
    })
```

2023-12-27 21:36 UTC, mcollina approved these changes
lgtm

2023-12-28 08:39 UTC, gurgunday commented on test/multipart-update-options-type.test.js
> +test('Should throw RequestFileTooLargeError when throwFileSizeLimit: false for file())', async function (t) {
```suggestion
test('Should throw RequestFileTooLargeError when throwFileSizeLimit: true for file())', async function (t) {

```

2023-12-28 08:41 UTC, gurgunday commented on test/multipart-update-options-type.test.js
> +test('Should throw RequestFileTooLargeError when throwFileSizeLimit: false for files())', async function (t) {
```suggestion
test('Should throw RequestFileTooLargeError when throwFileSizeLimit: true for files())', async function (t) {
```

2024-01-01 08:59 UTC, mcollina approved these changes
lgtm

2024-01-01 08:59 UTC, merged