Support firebase
fastify/fastify-multipart pull request #548
Opened 2024-10-08 09:31 UTC by ThomasKientz

Currently we can't use this plugin with [serverless](https://fastify.dev/docs/latest/Guides/Serverless/) GCP (or Firebase).

As explained here https://github.com/fastify/fastify/issues/946#issuecomment-766319521 and [in the doc for firebase](https://fastify.dev/docs/latest/Guides/Serverless/#add-custom-contenttypeparser-to-fastify-instance-and-define-endpoints), we need to use `req.rawBody` in order to parse files from multipart.

2024-10-08 09:40 UTC, Uzlopak commented
the tests are not happy

2024-10-08 09:54 UTC, gurgunday requested changes
Decorate that new assignment to req please

2024-10-08 11:14 UTC, Uzlopak commented on index.js
> +  fastify.decorateRequest('rawBody', req.rawBody)
you decorate the request when you register the plugin. then yo can assign rawbody to the fastify request.

2024-10-08 12:37 UTC, ThomasKientz commented
> the tests are not happy

 @Uzlopak don't really understand why it's failing, looks good but return exit code 1

2024-10-08 12:47 UTC, Uzlopak commented
The test coverage is Not 100%

2024-10-09 05:52 UTC, climba03003 reviewed
Where is `payload.rawBody` comes from?
I don't like the current idea to support one serverless environment and adding extra branching.

Instead one should provide a `plugin` that dedicated for the serverless environment and add all the necessary patching to match how `Node.js` works.

2024-10-10 08:49 UTC, Uzlopak commented
Well the problem is, that gcf is a glorified express router. So they preparse the body so that you dont have to. You get the body stream in rawBody. So maybe we need, like you suggest, a plugin which basically removes the default content type parsers and just assigns rawbody to body?!

2024-10-10 09:01 UTC, climba03003 commented
What's comes my mind is something like?

```js
function gcp(fastify) {
  // add pass through content-type parser
  fastify.addContentTypeParser('application/json', {}, (req, body, done) => {
    done(null, body.body);
  });
  
  // add stream transform for multipart when neccessary
  if (fastify.hasContentTypeParser('multipart/form-data')) {
    fastify.addHook('preParsing', function(request, reply, payload, done) {
      if(request.headers['content-type'].startsWith('multipart/form-data')) {
        // we override the `.pipe` method and return rawBody as new payload
        const pipe = request.pipe
        request.pipe = function(stream) {
          Readable.from([rawBody]).pipe(stream)
        }
        done(null, payload.rawBody)
      } else {
        done(null, payload)
      }
    })
  }
}
```

2024-10-14 08:06 UTC, ThomasKientz commented
Should I pursue the current implementation of this pull request and add test coverage? @Uzlopak

2026-06-03 07:44 UTC, closed without merging